[features]
seeds = false
safety_checks = true
[programs.localnet]
solana_twitter = "65rXkFFfKUZc6uN8NSSmc8gjax9aN6wMRi7NoVC1LRt7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/gazon/.config/solana/localhost.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
